@url = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzI0NTQ2MzcsInVzZXJfaWQiOiJiNjFiNTk2Ny04ZmJlLTQ4YWEtYmM1MC05ZmVlOWMzMTY0ZTAifQ.oWRSX_4JHSkL4go6zTWykRGDJoMuKYt8Ujexcrz2z34

### REGISTER
POST {{url}}/register HTTP/1.1
Content-Type: application/json

{
  "name": "ininame",
  "email": "ini@email.com",
  "password": "inipassword"
}

### LOGIN
POST {{url}}/login HTTP/1.1
Content-Type: application/json

{
  "email": "ini@email.com",
  "password": "inipassword"
}

### CREATE TASK
POST {{url}}/task HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "title task test",
  "description": "description test"
}