// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const countTaskByUser = `-- name: CountTaskByUser :one
SELECT COUNT(*) FROM tasks WHERE user_id = $1
`

func (q *Queries) CountTaskByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTaskByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO
    tasks (user_id, title, description)
VALUES ($1, $2, $3)
RETURNING
    id, user_id, title, description, status, created_at, updated_at
`

type CreateTaskParams struct {
	UserID      uuid.UUID
	Title       string
	Description *string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, arg.UserID, arg.Title, arg.Description)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, user_id, title, description, status, created_at, updated_at FROM tasks WHERE id = $1 AND user_id = $2
`

type GetTaskByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTaskByUser = `-- name: ListTaskByUser :many
SELECT id, user_id, title, description, status, created_at, updated_at
FROM tasks
WHERE
    user_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET
    $3
`

type ListTaskByUserParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListTaskByUser(ctx context.Context, arg ListTaskByUserParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTaskByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStatus = `-- name: UpdateStatus :execrows
UPDATE tasks SET status = $3 WHERE id = $2 AND user_id = $1
`

type UpdateStatusParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
	Status TaskStatus
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStatus, arg.UserID, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
    title = $3,
    description = $4,
    updated_at = now()
WHERE
    id = $2
    and user_id = $1
RETURNING
    id, user_id, title, description, status, created_at, updated_at
`

type UpdateTaskParams struct {
	UserID      uuid.UUID
	ID          uuid.UUID
	Title       string
	Description *string
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.UserID,
		arg.ID,
		arg.Title,
		arg.Description,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
