// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: token.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createToken = `-- name: CreateToken :exec
INSERT INTO
    tokens (id, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING
    id
`

type CreateTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.Exec(ctx, createToken, arg.ID, arg.UserID, arg.ExpiresAt)
	return err
}

const replaceToken = `-- name: ReplaceToken :execrows
UPDATE tokens
SET
    replaced_by = $2
WHERE
    id = $1
    AND replaced_by IS NULL
    AND revoked_at IS NULL
    AND expires_at > now()
`

type ReplaceTokenParams struct {
	ID         uuid.UUID
	ReplacedBy pgtype.UUID
}

func (q *Queries) ReplaceToken(ctx context.Context, arg ReplaceTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, replaceToken, arg.ID, arg.ReplacedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAllToken = `-- name: RevokeAllToken :execrows
UPDATE tokens
SET
    revoked_at = now()
WHERE
    user_id = $1
    AND revoked_at IS NULL
`

func (q *Queries) RevokeAllToken(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllToken, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeToken = `-- name: RevokeToken :execrows
UPDATE tokens
SET
    revoked_at = now()
WHERE
    id = $1
    AND revoked_at IS NULL
`

func (q *Queries) RevokeToken(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
